trigger: none
pr: none

resources: 
  pipelines:
  - pipeline: ci-pipeline
    source: nodebrady-ci
    trigger:
      enabled: true
      branches:
        include:
          - master

stages:
- template: ../common/templates/stages.yml  # Template reference
  parameters:
    component: nodebrady
