trigger:
  batch: true
  branches:
    include: 
    - '*'
  paths:
    include: 
    - nodebrady
    - common/ci-steps-template.yml

pr: none

jobs:
- template: ../common/ci-job-template.yml
  parameters:
    component: nodebrady
