trigger:
  batch: true
  branches:
    include: 
    - '*'
  paths:
    include: 
    - parrot
    
pr: none

stages:
- template: ../_devops/azure-pipelines/templates/stages.yml
  parameters:
    component: parrot
