trigger:
  batch: true
  branches:
    include: 
    - '*'
  paths:
    include: 
    - parrot
    
pr: none

variables:
  - template: ../_devops/azure-pipelines/templates/vars.yml
  parameters:
    component: parrot

stages:
- template: ../_devops/azure-pipelines/templates/stages.yml
  parameters:
    component: parrot
