trigger:
  batch: true
  branches:
    include: 
    - '*'
  paths:
    include: 
    - parrot
    - common/ci-steps-template.yml
    
pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- template: ../common/ci-vars-template.yml
  parameters:
      projectName: parrot

steps:
- template: ../common/ci-steps-template.yml
