version: "3.7"

#-----------------------------------------------------------------------
x-base: &base
  logging:
    driver: "json-file"
    options:
      max-size: "3m"
      max-file: "1"
  # https://docs.docker.com/compose/compose-file/#restart
  restart: ${DOCKER_RESTART:-unless-stopped}

#-----------------------------------------------------------------------
services:
  captainkube:
    <<: *base
    build:
      context: captainkube
    depends_on: [ 'parrot']

  parrot:
    <<: *base
    build:
      context: parrot
    ports: ['8080:80']

  phippy:
    <<: *base
    build:
      context: phippy
    ports: ['8081:80', '3333:3333']

  nodebrady:
    <<: *base
    build:
      context: nodebrady
    ports: ['3000:3000']
