version: "3.7"

#-----------------------------------------------------------------------
x-base: &base
  logging:
    driver: "json-file"
    options:
      max-size: "3m"
      max-file: "1"
  # https://docs.docker.com/compose/compose-file/#restart
  restart: ${DOCKER_RESTART:-unless-stopped}

#-----------------------------------------------------------------------
services:
  captainkube:
    <<: *base
    build:
      context: captainkube

  parrot:
    <<: *base
    build:
      context: parrot
