trigger:
  batch: true
  branches:
    include: 
    - '*'
  paths:
    include: 
    - phippy
    - common/ci-steps-template.yml
    
pr: none

jobs:
- template: ../common/ci-job-template.yml
  parameters:
    component: phippy
