replicaCount: 1
image:
  useImagePullSecrets: false
  pullPolicy: Always
service:
  internalPort: 80
  externalPort: 80
ingress:
  enabled: true
  #basedomain: <REPLACE WITH YOUR OWN AKS CLUSTER>.<YOUR REGION>.aksapp.io # replace with your own from the portal
  basedomain: 625dda48de0145bfa3c7.eastus.aksapp.io
