# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops
parameters:
  component: '_unset_'  # defaults for any parameters that aren't specified
  k8sNamespace: 'phippyandfriends'
  pool:
    vmImage: 'ubuntu-latest'
  dependsOn: ''

stages:
- stage: development
  displayName: development
  variables:
  - template: cd-vars-template.yml
    parameters:
      projectName: ${{ parameters.component }}
      # define 3 more variables: registryName, registryLogin and registryPassword in the Azure pipeline UI definition
  jobs:
  - deployment: development
    displayName: "Deploy '${{ parameters.component }}'"
    pool: ${{ parameters.pool }}
    environment: development-$(projectName)
    strategy:
      runOnce:
        deploy:
          steps:
          - template: cd-steps-template.yml
