steps:
# ---- docker ---
- bash: |
    cd $(projectName)
    docker build \
        -t $(registryServerName)/$(imageName):$(imageTag) \
        .
  displayName: 'docker build'
  failOnStderr: true

# push on master only
- bash: |
    echo $(registryPassword) | docker login \
        $(registryServerName) \
        -u $(registryLogin) \
        --password-stdin
  displayName: 'docker login'
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))
- bash: |
    docker push $(registryServerName)/$(imageName):$(imageTag)
  displayName: 'docker push'
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))
  failOnStderr: true

# ---- helm ---
- task: HelmInstaller@1
  displayName: 'install helm'
  inputs:
    helmVersionToInstall: $(helmVersion)

- bash: |
    cd $(projectName)
    helm package \
        --version $(helmChartVersion) \
        --app-version $(imageTag) \
        charts/$(projectName)
  displayName: 'helm package'
  failOnStderr: true
# push on master only
- bash: |
    cd $(projectName)
    chartPackage=$(ls $(projectName)-*.tgz)
    az acr helm push \
        -n $(registryName) \
        -u $(registryLogin) \
        -p $(registryPassword) \
        $chartPackage
  name: helmPush
  displayName: 'az acr helm push'
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))
  failOnStderr: true
  
# ---- variables.json ---
- publish: $(build.artifactStagingDirectory)
  artifact: build-artifact
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))
