# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#download
steps:
- checkout: none
- task: HelmInstaller@1
  displayName: 'install helm'
  inputs:
    helmVersionToInstall: $(helmVersion)
- bash: |
    az login \
        --service-principal \
        -u $(aksSpId) \
        -p $(aksSpSecret) \
        --tenant $(aksSpTenantId)
    az aks get-credentials \
        -n $(aks) \
        -g $(rg)
    helm repo add \
        $(registryName) \
        https://$(registryServerName)/helm/v1/repo \
        --username $(registryLogin) \
        --password $(registryPassword)
    helm upgrade \
        --namespace $(k8sNamespace) \
        --install \
        --wait \
        --version $(helmChartVersion) \
        --set image.repository=$(registryServerName)/$(projectName) \
        --set ingress.enabled=false \
        $(projectName) \
        $(registryName)/$(projectName)
  failOnStderr: true
  displayName: 'deploy helm chart'
