# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops
parameters:
  projectName: phippyandfriends
  component: '_unset_'
  pool:
    vmImage: 'ubuntu-latest'

stages:
# ---- infrastructure ---
- stage: infrastructure
  displayName: infrastructure
  jobs:
  - job: infrastructure_${{ parameters.component }}
    displayName: "Setup '${{ parameters.component }}'"
    pool: ${{ parameters.pool }}
    steps:
    - template: infrastructure-steps.yml

# ---- build ---
- stage: build
  displayName: build
  dependsOn:
    - infrastructure
  jobs:
  - job: build_${{ parameters.component }}
    displayName: "Build '${{ parameters.component }}'"
    pool: ${{ parameters.pool }}
    steps:
    - template: build-steps.yml

# ---- development ---
- stage: development
  displayName: development
  condition: and(succeeded('build'), eq(variables['Build.SourceBranchName'], 'master'))
  dependsOn:
    - build
  jobs:
  - deployment: deploy_${{ parameters.component }}
    displayName: "Deploy '${{ parameters.component }}'"
    pool: ${{ parameters.pool }}
    environment: ${{ parameters.projectName }}-dev
    strategy:
      runOnce:
        deploy:
          steps:
          - template: deploy-steps.yml
