parameters:
  projectName: 'hello-aks' # project directory
  component: '' # required: project/component to build/deploy
  # seabhel: https://www.fantasynamegenerators.com/marvel-celestial-names.php
  resourceId: 'seabhel' # seabhel=dev/test

variables:
# -- azure
# not PII according to https://stackoverflow.com/a/45663968/2592915
# - az account list --query "[].{name:name, subscriptionId:id, tenantId:tenantId}"
- name: armSubscriptionId
  value: your-subscription-id
- name: armTenantId
  value: your-tenant-id

#--- linked groups
# Pipeline variables to be defined in Azure UI
# group `arm` (az account list --query "[].{name:name, subscriptionId:id, tenantId:tenantId}")
# - armSubscriptionId (Azure Subscription Id)
# - armTenantId       (Azure Tenant Id)
# - armClientId      (Azure SPN Client Id)
# - armClientSecret  (Azure SPN Client Secret)
# - armAccessKey     (Access Key to Azure Storage Account for Terraform stat backend)
- group: arm
# group `acr` (TODO: Replace by Terraform output of ACR creation `admin_user_password`)
# - registryPassword (ACR password)
- group: acr
# group `sonar`
# - sonar.login
- group: sonar

#--- common
- name: projectName
  value: ${{ parameters.projectName }}
- name: resourceId
  value: ${{ parameters.resourceId }}
- name: resourcePrefix
  value: $(projectName)-$(resourceId)

  # https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#system-variables
- name: stage
  value: $(System.StageName)
- name: component
  value: ${{ parameters.component }}

#--- resource names
- name: rg
  value: $(resourcePrefix)-rg
- name: registryName
  value: helloaks$(resourceId)acr # NOTE: must not contain dashes!
- name: aks
  value: $(resourcePrefix)-aks

#------
# TODO: Separate this lumped together variables

# https://github.com/helm/helm/releases
# https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md#ubuntu-18044-lts
- name: helmVersion
  value: 3.1.2

  # --- docker
- name: registryLogin
  value: $(registryName)
- name: registryServerName
  value: $(registryName).azurecr.io
- name: dockerImage
  value: $(registryServerName)/$(component)
  # TODO: latest? --> #332
- name: dockerImageTag
  #value: $(build.buildId)
  value: latest

  # The k8s namespace = project-stage (ttdigital-develeopment, ttdigital-test, ...)
- name: k8sNamespace
  value: $(projectName)-$(stage)

  # TODO: for dev/test ok maybe false, for prod should be true
- name: ingressEnabled
  value: true
  # TODO: Get from terraform output `aks_basedomain` or
  # az aks show -n $(aks) -g $(rg) --query addonProfiles.httpApplicationRouting.config.HTTPApplicationRoutingZoneName
- name: ingressBaseDomain
  value: 129a383d656f4cfebf71.eastus.aksapp.io

  #
- name: helmChartVersion
  #value: latest
  value: $(build.buildId)
- name: helmChartPackage
  value: $(component)
- name: helmChartName
  value: $(registryName)/$(helmChartPackage)
# Helm Release Naming conventions, cf.:
# - https://github.com/helm/helm/issues/2062#issuecomment-461903079
# - https://www.reddit.com/r/devops/comments/bpowq3/what_is_your_helm_release_naming_convention/
- name: helmRelease
  value: $(k8sNamespace)-$(helmChartPackage)
