# TODO: pipeline variables to define in Azure UI
# group `arm` (az account list --query "[].{name:name, subscriptionId:id, tenantId:tenantId}")
# - armSubscriptionId (Azure Subscription Id)
# - armTenantId       (Azure Tenant Id)
# - armClientId       (Azure SPN Client Id)
# - armClientSecret   (Azure SPN Client Secret)
# - armAccessKey      (Access Key to Azure Storage Account for Terraform stat backend)
# group `acr` (TODO: Can remove?)
# - registryPassword (ACR password)

parameters:
  projectName: 'phippyandfriends'
  component: '' # project/component to build/deploy
  k8sNamespace: 'phippyandfriends' # k8s namespace to deploy to
  # seabhel: https://www.fantasynamegenerators.com/marvel-celestial-names.php
  stageId: 'seabhel' # seabhel=dev/test

variables:
#--- link groups
- group: arm
- group: acr

#--- common
- name: projectName
  value: ${{ parameters.projectName }}
- name: component
  value: ${{ parameters.component }}
- name: stageId
  value: ${{ parameters.stageId }}

#--- resource names
- name: rg
  value: $(projectName)-$(stageId)-rg
- name: registryName
  value: $(projectName)$(stageId)acr
- name: aks
  value: $(projectName)-$(stageId)-aks

  #------
  # https://github.com/helm/helm/releases
- name: helmVersion
  value: 3.1.1
  #
- name: registryLogin
  value: $(registryName)
- name: registryServerName
  value: $(registryName).azurecr.io
- name: dockerReferenceBase
  value: $(registryServerName)/$(projectName)
  # TODO: latest?
- name: imageTag
  value: $(build.buildId)
- name: helmChartVersion
  value: $(build.buildId)
  #
- name: k8sNamespace
  value: ${{ parameters.k8sNamespace }}