trigger:
  batch: true
  branches:
    include: 
    - '*'
  paths:
    include: 
    - captainkube
    
pr: none

stages:
- template: ../_devops/azure-pipelines/templates/stages.yml
  parameters:
    component: captainkube
