trigger: none
pr: none

resources: 
  pipelines:
  - pipeline: ci-pipeline
    source: captainkube-ci
    trigger:
      enabled: true
      branches:
        include:
          - master

stages:
- template: ../common/cd-stages-template.yml
  parameters:
    component: captainkube
